name: MyPocket
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  hexcolor: ^3.0.1
  http: ^1.4.0
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.2.0
  rename: ^3.1.0
  speech_to_text: 7.1.0
  table_calendar: ^3.1.1
  flutter_local_notifications: ^17.1.2
  flutter_staggered_animations: ^1.1.1 
  timezone: ^0.9.3
  intl: 0.19.0 
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  avatar_glow: ^3.0.1
  permission_handler: ^11.3.1
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  
  # --- Icono para iOS y versiones antiguas de Android ---
  # Aquí usamos tu imagen original completa, ya que estos sistemas no usan iconos adaptativos.
  image_path: "assets/images/logo.png" # Pon aquí la ruta a tu imagen original
  
  min_sdk_android: 21
  
  # --- Configuración del Icono Adaptativo para Android ---
  # Aquí es donde ocurre la magia.
  adaptive_icon_background: "assets/images/logo_background.png" # La imagen del fondo degradado
  adaptive_icon_foreground: "assets/images/logo_foreground.png" # La imagen del logo con transparencia

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/svg/

  fonts:
    - family: Baloo2
      fonts:
        - asset: assets/fonts/Baloo2-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Baloo2-Bold.ttf
          weight: 700
        - asset: assets/fonts/Baloo2-Medium.ttf
          weight: 500
        - asset: assets/fonts/Baloo2-Regular.ttf
          weight: 400
        - asset: assets/fonts/Baloo2-SemiBold.ttf
          weight: 600